[package]
name = "magic"
description = "libmagic bindings"
readme = "README.md"
license = "MIT"
keywords = ["magic", "binding", "file"]
categories = ["api-bindings"]
repository = "https://github.com/robo9k/rust-magic"
documentation = "https://docs.rs/magic"
authors = [
	"Daniel Micay <danielmicay@gmail.com>",
	"Petar Radošević <petar@wunki.org>",
	"lilydjwg <lilydjwg@gmail.com>",
	"Jeff Belgum <belgum@bastille.io>",
	"Onur Aslan <onur@onur.im>",
	"robo9k <robo@9k.lv>",
]
version = "0.12.2"
exclude = [
    ".gitignore",
]
rust-version = "1.46"

[package.metadata]
msrv = "1.46.0"

[lib]
name = "magic"

[dependencies]
bitflags = "1.3.2"
magic-sys = "0.2.1"

[dependencies.libc]
version = "0.2.105"
default-features = false

[dev-dependencies]
regex = "1.5.4"
