name: cargo deny

permissions:
  contents: read

on:
  push:
    branches: [ main ]
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/deny.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/deny.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - uses: EmbarkStudios/cargo-deny-action@7257a18a9c2fe3f92b85d41ae473520dff953c97 # v1.3.2
      with:
        command: check ${{ matrix.checks }}
        arguments: --all-features
